package com.hotelalura.model;

public enum Nacionalidade {
    AMERICANO, AUSTRALIANO, BRASILEIRO, BRITÂNICO, CANADENSE, CHINÊS, DINAMARQUÊS, HOLANDÊS, EGÍPCIO, FRANCÊS,
    ALEMÃO, GREGO, INDIANO, IRLANDÊS, ISRAELENSE, ITALIANO, JAPONÊS, COREANO, MEXICANO, NEOZELANDÊS, NORUEGUÊS,
    POLONÊS, PORTUGUÊS, RUSSO, ESPANHOL, SUECO, SUÍÇO, TURCO, UCRANIANO, VIETNAMITA;
}